name: Deploy java app to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with maven
        run: mvn clean package

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload JAR to VM using az scp
        run: |
          az scp --local-path target/*.jar \
                 --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                 --vm-name ${{ secrets.AZURE_VM_NAME }} \
                 --username ${{ secrets.AZURE_VM_USERNAME }} \
                 --destination-path /home/${{ secrets.AZURE_VM_USERNAME }}/app/ \
                 --recursive

      - name: Run Java App on Azure VM
        run: |
          az vm run-command invoke \
            --command-id RunShellScript \
            --name ${{ secrets.AZURE_VM_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --scripts "pkill -f 'java -jar' || true && nohup java -jar /home/${{ secrets.AZURE_VM_USERNAME }}/app/*.jar > /home/${{ secrets.AZURE_VM_USERNAME }}/app/app.log 2>&1 &"